#!/usr/bin/env python3
"""
fetch_income_brackets.py — Fetch net price by income bracket from College Scorecard.

Outputs income.js: window.ROI_INCOME = { schoolSlug: [net0,net1,net2,net3,net4], ... }
Each value is the net price (what the student pays) for that bracket, or null.
Brackets: $0-30k, $30-48k, $48-75k, $75-110k, $110k+

calc/UI derives: aid = max(0, sticker - net)

Usage:
  python fetch_income_brackets.py --key YOUR_API_KEY [--states AL,...] [--out income.js]
"""

import argparse
import json
import re
import sys
import time
import urllib.request
import urllib.parse

BASE_URL = "https://api.data.gov/ed/collegescorecard/v1/schools"

ALL_STATES = [
    "AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN",
    "IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH",
    "NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT",
    "VT","VA","WA","WV","WI","WY",
]

BRACKETS = ["0-30000", "30001-48000", "48001-75000", "75001-110000", "110001plus"]

FIELDS = ",".join([
    "id",
    "school.name",
    "school.state",
] + [f"latest.cost.net_price.public.by_income_level.{b}" for b in BRACKETS]
  + [f"latest.cost.net_price.private.by_income_level.{b}" for b in BRACKETS])


def slugify(name):
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")[:40]


def fetch_page(key, state, page):
    params = {
        "school.state": state,
        "school.operating": 1,
        "fields": FIELDS,
        "per_page": 100,
        "page": page,
        "api_key": key,
    }
    url = BASE_URL + "?" + urllib.parse.urlencode(params)
    for attempt in range(3):
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                return json.loads(r.read())
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")[:300]
            if e.code == 429:
                print("  Rate limited, waiting 5s…", file=sys.stderr)
                time.sleep(5)
                continue
            print(f"HTTP {e.code} for {state} page {page}: {body}", file=sys.stderr)
            return None
        except Exception as e:
            print(f"Error {state} page {page}: {e}", file=sys.stderr)
            if attempt < 2:
                time.sleep(2)
            else:
                return None
    return None


def extract(r):
    name = r.get("school.name") or ""
    if not name:
        return None, None

    school_id = slugify(name)
    nets = []
    for b in BRACKETS:
        pub  = r.get(f"latest.cost.net_price.public.by_income_level.{b}")
        priv = r.get(f"latest.cost.net_price.private.by_income_level.{b}")
        val  = pub if pub is not None else priv
        nets.append(round(val) if val is not None else None)

    if all(v is None for v in nets):
        return school_id, None

    return school_id, nets


def fetch_state(key, state):
    result = {}
    page = 0
    while True:
        data = fetch_page(key, state, page)
        if not data:
            break
        rows = data.get("results", [])
        if not rows:
            break
        for r in rows:
            sid, nets = extract(r)
            if sid and nets:
                result[sid] = nets
        total = data.get("metadata", {}).get("total", 0)
        if min((page + 1) * 100, total) >= total:
            break
        page += 1
        time.sleep(0.1)
    return result


def write_income_js(all_income, out_path):
    lines = [
        "// income.js — Net price by income bracket from College Scorecard.",
        "// Auto-generated by fetch_income_brackets.py — do not edit by hand.",
        "// Brackets: [$0-30k, $30-48k, $48-75k, $75-110k, $110k+] (null = no data).",
        "// UI derives aid = max(0, sticker - net_price[bracketIdx]).",
        "window.ROI_INCOME = {",
    ]
    for sid in sorted(all_income):
        nets = all_income[sid]
        vals = ",".join("null" if v is None else str(v) for v in nets)
        lines.append(f'  "{sid}":[{vals}],')
    lines.append("};")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out_path} ({len(all_income)} schools)")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--key",    required=True)
    parser.add_argument("--states", default=None)
    parser.add_argument("--out",    default="income.js")
    args = parser.parse_args()

    states = [s.strip().upper() for s in args.states.split(",")] if args.states else ALL_STATES
    all_income = {}

    for i, state in enumerate(states):
        print(f"[{i+1}/{len(states)}] {state}…", file=sys.stderr)
        for sid, nets in fetch_state(args.key, state).items():
            if sid not in all_income:
                all_income[sid] = nets

    write_income_js(all_income, args.out)


if __name__ == "__main__":
    main()
